### ISSUE TITLE
version reference issue

### ISSUE THREAD

**Issue by t-j-h** [PeculiarVentures/pkcs11js#33]
"This was developed to the PKCS#11 2.3 specification, the 2.4 headers were not availible at the time we created this, it should be easy enough to extend it for the new version at a later date."

This needs to be corrected - there is no such version as 2.3 or 2.4 - there is 2.30 and 2.40
The official current version is 2.40 
The OASIS PKCS#11 technical committee are working on 3.0

**Comment by rmhrisk** [comment]
@t-j-h I have updated the readme to go to two decimal places instead of one. You can see that change here: https://github.com/PeculiarVentures/pkcs11js/commit/f6f46336994f3b7cc04a9714717bc9ba32ee0c4f

When we created this library there was no finalized 2.40 version, and we can not support a new version without headers and implementations to test to.

If you have headers for 2.40 and can point us at a device that supports it we can certainly add it when the time is available.
